const horses = [
{ "name": "	DATOS MARIANNA	", "number": "	1	" },
{ "name": "	LEW'S JACKIE	", "number": "	1	" },
{ "name": "	SOBEL PROMISE	", "number": "	2	" },
{ "name": "	DO IT DOROTHY	", "number": "	2	" },
{ "name": "	SHE'S SHE	", "number": "	3	" },
{ "name": "	L'AMIRAL WHO'S WHO	", "number": "	3	" },
{ "name": "	GREEN PEAK	", "number": "	4	" },
{ "name": "	KO SAMUI	", "number": "	4	" },
{ "name": "	EIGHT HOUR	", "number": "	4	" },
{ "name": "	GLOBAL FIZZ	", "number": "	4	" },
{ "name": "	HOLIDAY AC	", "number": "	5	" },
{ "name": "	SERENA ZON	", "number": "	5	" },
{ "name": "	AL'S SUPERSUB	", "number": "	6	" },
{ "name": "	GEMSTONE AZE	", "number": "	6A	" },
{ "name": "	MOTSON	", "number": "	7	" },
{ "name": "	I'M WHO	", "number": "	7A	" },
{ "name": "	BLACK FIRE	", "number": "	8	" },
{ "name": "	CANTAL	", "number": "	8	" },
{ "name": "	UNIVERSAL TILE	", "number": "	9	" },
{ "name": "	HEAVY FOOT	", "number": "	9	" },
{ "name": "	MY FIRST LADY	", "number": "	9	" },
{ "name": "	CAMELIA	", "number": "	9	" },
{ "name": "	BEACHCOMBER	", "number": "	10	" },
{ "name": "	PLACE ROYAL	", "number": "	10	" },
{ "name": "	L'AMIRAL SJ'S	", "number": "	10	" },
{ "name": "	LUCIFER SAM	", "number": "	10	" },
{ "name": "	TOBY BAROSSO	", "number": "	11	" },
{ "name": "	INKASSO SIMONI	", "number": "	12	" },
{ "name": "	DARE TO DREAM	", "number": "	12	" },
{ "name": "	KREADLY'S LEW	", "number": "	13	" },
{ "name": "	STAN WAWRINKA	", "number": "	14	" },
{ "name": "	AZZURRO	", "number": "	15	" },
{ "name": "	FIRST WISE L.	", "number": "	16	" },
{ "name": "	EARNED INCOME	", "number": "	16A	" },
{ "name": "	FOREST WOOD	", "number": "	17	" },
{ "name": "	SABATINO BO	", "number": "	18	" },
{ "name": "	MAJOR H.	", "number": "	18A	" }
];
localStorage.setItem('granliden_horses', JSON.stringify(horses));
