const horses = [
{ "name": "	NATORP BO	", "number": "	3	" },
{ "name": "	UPSET TILE	", "number": "	21	" },
{ "name": "	GUSTAV SIMONI	", "number": "	23	" },
{ "name": "	SHEISPROPULSION	", "number": "	24	" },
{ "name": "	UNDER ARMOUR	", "number": "	23	" },
{ "name": "	EPICURE	", "number": "	4	" },
{ "name": "	ULTIMO TILE	", "number": "	24	" },
{ "name": "	BARON D.SOX	", "number": "	23	" },
{ "name": "	YTOWNS ULRIK	", "number": "	23	" },
{ "name": "	GLOBAL EVERYWHERE	", "number": "	23	" },
{ "name": "	PAPA HOCKE	", "number": "	20A	" },
{ "name": "	NESSUNO IN PJ'S	", "number": "	20	" },
{ "name": "	BONAFONTE	", "number": "	20	" },
{ "name": "	JAPIRO POWER	", "number": "	16	" },
{ "name": "	GRAFFITI BRODDA	", "number": "	17	" },
{ "name": "	VINCE WYNN	", "number": "	12A	" },
{ "name": "	MONESY	", "number": "	12	" },
{ "name": "	MILES AWAY	", "number": "	14	" },
{ "name": "	GLOBAL HIGHFLYER	", "number": "	13A	" },
{ "name": "	MILLIE'S GAME	", "number": "	13	" },
{ "name": "	ROYAL WIBB	", "number": "	22	" },
{ "name": "	ALLSTAR	", "number": "	11	" },
{ "name": "	FACE TIME H.	", "number": "	10A	" },
{ "name": "	LEW'S LADYBIRD	", "number": "	19	" },
{ "name": "	LE PEAK	", "number": "	23	" },
{ "name": "	GARLESS	", "number": "	22A	" },
{ "name": "	PEAK ROYAL SCOT	", "number": "	15	" },
{ "name": "	LICENSE TO CRUZADE	", "number": "	15	" },
{ "name": "	LORENS FLEVO	", "number": "	23	" },
{ "name": "	YTOWNS MAGNIFIK	", "number": "	2	" },
{ "name": "	STARO THUNDERROAD	", "number": "	1A	" },
{ "name": "	JEANS N'EPOWER	", "number": "	23	" },
{ "name": "	SPACEMAN JOG	", "number": "	10	" },
{ "name": "	GAME CHANGER	", "number": "	5	" },
{ "name": "	HENESSI JOY	", "number": "	1	" },
{ "name": "	GLOBAL ACTION	", "number": "	24	" },
{ "name": "	UNFORGETTABLE TILE	", "number": "	6	" },
{ "name": "	M.T.URUS	", "number": "	11A	" },
{ "name": "	L'AMIRAL READLY	", "number": "	24	" },
{ "name": "	GLOBAL HIPPIE	", "number": "	16	" },
{ "name": "	GLOBAL HOTLIPS	", "number": "	16	" },
{ "name": "	LEW'S JILL	", "number": "	18	" },
{ "name": "	GRANDMA SELMA R.P.	", "number": "	17	" },
{ "name": "	ROCK'N ROLF R.P.	", "number": "	14A	" },
{ "name": "	SQUEEZE'EM	", "number": "	12	" },
{ "name": "	ICHIRO D'ARC	", "number": "	14	" },
{ "name": "	GLOBAL HIGHCLASS	", "number": "	15A	" },
{ "name": "	PLAYITHOT	", "number": "	13	" },
{ "name": "	DIAMOND SNAPPER	", "number": "	21A	" },
{ "name": "	TAURUS TILE	", "number": "	7	" },
{ "name": "	PATRIOT NEWPORT	", "number": "	8	" },
{ "name": "	FIVE CARAT	", "number": "	9	" },
{ "name": "	NICK NACK MEARAS	", "number": "	9	" },
{ "name": "	REIDAR DI QUATTRO	", "number": "	9A	" },
{ "name": "	GLOBAL HALO	", "number": "	16	" }
];

// Store the horse data in local storage
localStorage.setItem('kamparp_horses', JSON.stringify(horses));
